name: argoritimo
description: A simple command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.10.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.9.0
dependencies: 
  equatable: ^2.0.3
  mpesa_sdk_dart: ^1.0.0
